services:
  api:
    build: backend
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JWT_KEY=${JWT_KEY}
      - COOKIE_KEY=${COOKIE_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:80/api/v1/health"
        ]
      interval: ${INTERVAL}
      timeout: ${TIMEOUT}
      retries: ${RETRIES}
    depends_on:
      - postgres
  nginx:
    image: nginx:1.27
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: ${INTERVAL}
      timeout: ${TIMEOUT}
      retries: ${RETRIES}
    depends_on:
      - api
