services:
  - type: web
    name: applifting-api
    runtime: docker
    repo: https://github.com/StrawIII/applifting-api
    plan: free
    envVars:
      - key: RETRIES
        sync: false
      - key: TIMEOUT
        sync: false
      - key: INTERVAL
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: APPLIFTING_API_REFRESH_TOKEN
        sync: false
      - key: APPLIFTING_API_BASE_URL
        sync: false
    region: frankfurt
    healthCheckPath: /api/v1/health
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
