# Exported from Render on 2024-11-20T18:41:37Z
services:
  - type: web
    name: applifting-api
    runtime: python
    repo: https://github.com/StrawIII/applifting-api
    plan: free
    envVars:
      - key: RETRIES
        sync: false
      - key: TIMEOUT
        sync: false
      - key: INTERVAL
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: APPLIFTING_API_REFRESH_TOKEN
        sync: false
      - key: APPLIFTING_API_BASE_URL
        sync: false
    region: frankfurt
    buildCommand: pip3 install uv
    startCommand: uv run uvicorn api.main:app --host 0.0.0.0
version: "1"
