"""Add created_at, updated_at to product and add fetched_at to offer

Revision ID: 7f789df404dd
Revises: e0eee6e44dbd
Create Date: 2024-11-21 12:58:15.310669

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f789df404dd"
down_revision: Union[str, None] = "e0eee6e44dbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offer", sa.Column("fetched_at", postgresql.TIMESTAMP(), nullable=False)
    )
    op.add_column(
        "product", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False)
    )
    op.add_column(
        "product", sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    op.drop_column("offer", "fetched_at")
    # ### end Alembic commands ###
